extern unsigned int Renesas_H8_3297_Board_ADConverter_DataRegisterA;
extern unsigned int Renesas_H8_3297_Board_ADConverter_DataRegisterB;
extern unsigned int Renesas_H8_3297_Board_ADConverter_DataRegisterC;
extern char Renesas_H8_3297_Board_ADConverter_ControlStatusRegister;
extern char Renesas_H8_3297_Board_ADConverter_ControlRegister;
