typedef void (*Renesas_InterruptHandler) (void);

extern char Renesas_H8_3297_Board_WaitStateControlRegister;
extern char Renesas_H8_3297_Board_SerialTimerControlRegister;
extern char Renesas_H8_3297_Board_SystemControlRegister;
extern char Renesas_H8_3297_Board_ModeControlRegister;

extern char Renesas_H8_3297_Board_IrqSenseControlRegister;
extern char Renesas_H8_3297_Board_IrqEnableRegister;

extern Renesas_InterruptHandler Renesas_H8_3297_VectorTable_AfterReset;
extern Renesas_InterruptHandler Renesas_H8_3297_VectorTable_NonMaskableInterrupt;
extern Renesas_InterruptHandler Renesas_H8_3297_VectorTable_Irq0;
extern Renesas_InterruptHandler Renesas_H8_3297_VectorTable_Irq1;
extern Renesas_InterruptHandler Renesas_H8_3297_VectorTable_Irq2;
extern Renesas_InterruptHandler Renesas_H8_3297_VectorTable_Timer16Bit_InputCaptureA;
extern Renesas_InterruptHandler Renesas_H8_3297_VectorTable_Timer16Bit_InputCaptureB;
extern Renesas_InterruptHandler Renesas_H8_3297_VectorTable_Timer16Bit_InputCaptureC;
extern Renesas_InterruptHandler Renesas_H8_3297_VectorTable_Timer16Bit_InputCaptureD;
extern Renesas_InterruptHandler Renesas_H8_3297_VectorTable_Timer16Bit_OutputCompareA;
extern Renesas_InterruptHandler Renesas_H8_3297_VectorTable_Timer16Bit_OutputCompareB;
extern Renesas_InterruptHandler Renesas_H8_3297_VectorTable_Timer16Bit_Overflow;
extern Renesas_InterruptHandler Renesas_H8_3297_VectorTable_Timer8Bit_Channel0_OutputCompareA;
extern Renesas_InterruptHandler Renesas_H8_3297_VectorTable_Timer8Bit_Channel0_OutputCompareB;
extern Renesas_InterruptHandler Renesas_H8_3297_VectorTable_TimerBit_Channel0_Overflow;
extern Renesas_InterruptHandler Renesas_H8_3297_VectorTable_Timer8Bit_Channel1_OutputCompareA;
extern Renesas_InterruptHandler Renesas_H8_3297_VectorTable_Timer8Bit_Channel1_OutputCompareB;
extern Renesas_InterruptHandler Renesas_H8_3297_VectorTable_TimerBit_Channel1_Overflow;
extern Renesas_InterruptHandler Renesas_H8_3297_VectorTable_SerialCommunication_ReceiveError;
extern Renesas_InterruptHandler Renesas_H8_3297_VectorTable_SerialCommunication_ReceiveEnd;
extern Renesas_InterruptHandler Renesas_H8_3297_VectorTable_SerialCommunication_TdrEmpty;
extern Renesas_InterruptHandler Renesas_H8_3297_VectorTable_SerialCommunication_TsrEmpty;    
extern Renesas_InterruptHandler Renesas_H8_3297_VectorTable_ADConverter_ConversionEnd;    
extern Renesas_InterruptHandler Renesas_H8_3297_VectorTable_WatchdogTimer_Overflow;

#include "Port.h"
#include "Timer16Bit.h"
#include "Timer8Bit.h"
#include "WatchdogTimer.h"
#include "SerialCommunication.h"
#include "ADConverter.h"
