extern char Renesas_H8_3297_Board_SerialCommunication_SerialModeRegister;
extern char Renesas_H8_3297_Board_SerialCommunication_BitRateRegister;
extern char Renesas_H8_3297_Board_SerialCommunication_SerialControlRegister;
extern char Renesas_H8_3297_Board_SerialCommunication_TransmitDataRegister;
extern char Renesas_H8_3297_Board_SerialCommunication_SerialStatusRegister;
extern char Renesas_H8_3297_Board_SerialCommunication_ReceiveDataRegister;
