extern char Renesas_H8_3297_Board_Timer8Bit_Channel0_ControlRegister;
extern char Renesas_H8_3297_Board_Timer8Bit_Channel0_ControlStatusRegister;
extern char Renesas_H8_3297_Board_Timer8Bit_Channel0_ConstantRegisterA;
extern char Renesas_H8_3297_Board_Timer8Bit_Channel0_ConstantRegisterB;
extern char Renesas_H8_3297_Board_Timer8Bit_Channel0_Counter;

extern char Renesas_H8_3297_Board_Timer8Bit_Channel1_ControlRegister;
extern char Renesas_H8_3297_Board_Timer8Bit_Channel1_ControlStatusRegister;
extern char Renesas_H8_3297_Board_Timer8Bit_Channel1_ConstantRegisterA;
extern char Renesas_H8_3297_Board_Timer8Bit_Channel1_ConstantRegisterB;
extern char Renesas_H8_3297_Board_Timer8Bit_Channel1_Counter;

