#ifndef _IL_CONFIG_OPTIONS

#define IL_CONFIG_REDUCE_CODE n
#define IL_CONFIG_REDUCE_DATA n
#define IL_CONFIG_USE_THIN_LOCKS n
#define IL_CONFIG_DIRECT y
#define IL_CONFIG_UNROLL y
#undef IL_CONFIG_JAVA
#undef IL_CONFIG_GZIP
#define IL_CONFIG_LATIN1 n
#define IL_CONFIG_CACHE_PAGE_SIZE (128 * 1024)
#define IL_CONFIG_STACK_SIZE 8192
#define IL_CONFIG_FRAME_STACK_SIZE 512
#define IL_CONFIG_GC_HEAP_SIZE 0
#define IL_CONFIG_PINVOKE y
#define IL_CONFIG_REFLECTION y
#define IL_CONFIG_RUNTIME_INFRA y
#define IL_CONFIG_NETWORKING y
#define IL_CONFIG_FP_SUPPORTED y
#define IL_CONFIG_EXTENDED_NUMERICS y
#define IL_CONFIG_NON_VECTOR_ARRAYS y
#define IL_CONFIG_APPDOMAINS y
#define IL_CONFIG_REMOTING y
#define IL_CONFIG_VARARGS y
#define IL_CONFIG_GROW_FRAMES y
#define IL_CONFIG_FILTERED_EXCEPTIONS y
#define IL_CONFIG_DEBUG_LINES y
#define IL_CONFIG_FILESYSTEM y

#endif /* _IL_CONFIG_OPTIONS */
